# --- START OF FILE text-to-codebase.py ---
import os
import sys
import argparse
import re
import shutil

# --- Configuration ---
# This separator MUST match the one used in the generator script
FILE_CONTENT_SEPARATOR = " FILE CONTENTS "
START_DELIMITER_PATTERN = r"^--- Start of (.*?) ---$" # Regex to capture the relative path
DEFAULT_ENCODING = "utf-8"
# --- End Configuration ---

def parse_and_recreate(input_filepath, output_dir, force_overwrite=False, encoding=DEFAULT_ENCODING):
    """
    Parses the combined text file and recreates the directory structure and files.

    Args:
        input_filepath (str): Path to the text file generated by codebase-to-text.
        output_dir (str): The root directory where the structure will be created.
        force_overwrite (bool): If True, overwrite existing files in the output directory.
                                Otherwise, skip files that already exist.
        encoding (str): The encoding to use when reading the input file.

    Returns:
        tuple: (files_created_count, errors_list)
    """
    files_created = 0
    errors = []
    abs_output_dir = os.path.abspath(output_dir)

    # --- 1. Read the Input File ---
    try:
        with open(input_filepath, "r", encoding=encoding, errors="ignore") as f:
            full_content = f.read()
    except FileNotFoundError:
        errors.append(f"Error: Input file not found: {input_filepath}")
        return 0, errors
    except Exception as e:
        errors.append(f"Error reading input file {input_filepath}: {e}")
        return 0, errors

    # --- 2. Find the Separator ---
    # Construct the full separator line for searching
    # Assume the separator line looks like "===== SEPARATOR ====="
    # We need to find the core text part FILE_CONTENT_SEPARATOR
    separator_line_start = full_content.find(FILE_CONTENT_SEPARATOR)
    if separator_line_start == -1:
        errors.append(f"Error: File content separator ('{FILE_CONTENT_SEPARATOR}') not found in {input_filepath}. Invalid format.")
        # Attempt to process anyway if only content blocks exist? Risky. Let's require the separator.
        return 0, errors

    # Find the end of the separator line to get the start of actual content
    content_start_index = full_content.find('\n', separator_line_start)
    if content_start_index == -1:
        # Separator might be the last line? Unlikely but possible.
        content_section = "" # No content found after separator
    else:
        # Skip the newline itself and any potential blank lines after it
         content_start_index += 1
         while content_start_index < len(full_content) and full_content[content_start_index] in ('\n', '\r'):
             content_start_index += 1
         content_section = full_content[content_start_index:]


    # --- 3. Prepare Output Directory ---
    if not os.path.exists(abs_output_dir):
        try:
            os.makedirs(abs_output_dir)
            print(f"Created output directory: {abs_output_dir}")
        except Exception as e:
            errors.append(f"Error creating output directory {abs_output_dir}: {e}")
            return 0, errors
    elif not force_overwrite:
        # Check if directory is empty (or contains only .git or similar standard ignores)
        # A simple check is just os.listdir() length
        if os.listdir(abs_output_dir):
             # More robust check: iterate and see if any files *would* be overwritten
             pass # We will check per-file later if not force_overwrite

    # --- 4. Parse Content Section and Create Files ---
    # Use re.finditer to find all start delimiters and their positions
    matches = list(re.finditer(START_DELIMITER_PATTERN, content_section, re.MULTILINE))

    if not matches:
         if content_section.strip(): # Content exists but no delimiters found
              errors.append("Warning: Content section found, but no '--- Start of ... ---' delimiters were detected.")
         else:
              errors.append("Warning: No file content delimiters found after the separator line.")
         # Continue if errors list is empty (e.g. only tree was present)
         # If previous errors occurred, return now.
         if errors:
             return 0, errors


    num_matches = len(matches)
    for i, match in enumerate(matches):
        relative_path = match.group(1).strip()
        if not relative_path:
            errors.append(f"Warning: Found a start delimiter with an empty path near line {content_section[:match.start()].count('\\n')}. Skipping.")
            continue

        # Normalize the path separators for the target OS
        relative_path = os.path.normpath(relative_path)
        # Security: Prevent path traversal (e.g., '../../etc/passwd')
        if ".." in relative_path.split(os.path.sep):
             errors.append(f"Security Warning: Skipping potentially unsafe path: '{relative_path}'")
             continue

        dest_path = os.path.join(abs_output_dir, relative_path)
        dest_dir = os.path.dirname(dest_path)

        # --- Extract Content ---
        content_block_start_index = match.end() + 1 # Start after the delimiter line's newline
        # Find the end of this file's content
        if i + 1 < num_matches:
            # End is the start of the *next* delimiter line
            content_block_end_index = matches[i+1].start()
             # Backtrack to remove trailing newline before the next delimiter
            if content_block_end_index > 0 and content_section[content_block_end_index-1] == '\n':
                content_block_end_index -= 1
            if content_block_end_index > 0 and content_section[content_block_end_index-1] == '\r': # Handle \r\n
                 content_block_end_index -= 1
        else:
            # This is the last file, content goes to the end of the section
            content_block_end_index = len(content_section)

        file_content = content_section[content_block_start_index:content_block_end_index]

        # Optional: Clean trailing whitespace/newlines from the extracted content block?
        # file_content = file_content.rstrip() # Careful, might remove intended blank lines at end
        # Usually the format is `--- End of file ---\n\n--- Start of next ---`,
        # so the slicing should exclude the final `--- End of ... ---` line if it exists.
        # Let's find the expected end delimiter for this block if present.
        end_delimiter = f"--- End of {relative_path.replace(os.path.sep, '/')} ---" # Generator uses /
        end_delim_pos = file_content.rfind(end_delimiter)
        if end_delim_pos != -1:
             # Check if it's likely the actual end delimiter (e.g., near the end)
             # A simple check: is it on the last non-empty line?
             trimmed_content_for_check = file_content.rstrip()
             if trimmed_content_for_check.endswith(end_delimiter):
                 # Remove the delimiter and trailing whitespace/newlines before it
                 file_content = file_content[:end_delim_pos].rstrip()


        # --- Check for Overwrite ---
        if os.path.exists(dest_path) and not force_overwrite:
            print(f"Skipping existing file: {relative_path}")
            continue

        # --- Create Directories and Write File ---
        try:
            if not os.path.exists(dest_dir):
                os.makedirs(dest_dir)

            with open(dest_path, "w", encoding=encoding) as f_out:
                f_out.write(file_content)
            print(f"Created: {relative_path}")
            files_created += 1

        except Exception as e:
            error_msg = f"Error creating file {relative_path}: {e}"
            errors.append(error_msg)
            print(error_msg, file=sys.stderr) # Also print error immediately

    return files_created, errors


def main():
    parser = argparse.ArgumentParser(
        description="Recreate directory structure and files from a codebase-to-text output file.",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "input_file",
        help="Path to the combined text file generated by codebase-to-text."
    )
    parser.add_argument(
        "-o", "--output-dir",
        default=".",
        help="The root directory where the structure will be created (default: current directory)."
    )
    parser.add_argument(
        "-f", "--force",
        action="store_true",
        help="Overwrite existing files in the output directory. Use with caution!"
    )
    parser.add_argument(
        "--encoding",
        default=DEFAULT_ENCODING,
        help=f"Encoding to use for reading the input file (default: {DEFAULT_ENCODING})."
    )

    args = parser.parse_args()

    # --- Safety Check for Output Directory ---
    abs_output_dir = os.path.abspath(args.output_dir)
    if os.path.exists(abs_output_dir) and os.listdir(abs_output_dir) and not args.force:
        try:
             # Check if directory exists and is not empty
             response = input(f"Warning: Output directory '{abs_output_dir}' exists and is not empty.\n"
                              f"Continuing may overwrite files.\n"
                              f"Proceed? (yes/No): ").lower()
             if response != 'yes':
                  print("Operation cancelled.")
                  sys.exit(0)
             else:
                  print("Proceeding with potential overwrites (individual files will still be skipped unless --force is used)...")
                  # Note: File-level overwrite is still controlled by --force flag later
        except EOFError: # Handle non-interactive environments
             print(f"Warning: Output directory '{abs_output_dir}' exists and is not empty. Use --force to overwrite.", file=sys.stderr)
             sys.exit(1)


    # --- Run the Parser ---
    start_time = time.time()
    files_count, errors = parse_and_recreate(args.input_file, args.output_dir, args.force, args.encoding)
    end_time = time.time()
    duration = end_time - start_time

    # --- Report Results ---
    print("\n--- Operation Summary ---")
    if files_count > 0:
        print(f"Successfully created {files_count} file(s) in '{abs_output_dir}'.")
    else:
        print("No files were created.")

    if errors:
        print(f"\nEncountered {len(errors)} error(s)/warning(s):")
        for i, err in enumerate(errors):
            print(f"  {i+1}. {err}")
    else:
        if files_count > 0 : print("Operation completed successfully.")
        else: print("Operation completed, but no files were generated (check input format and selection).")


    print(f"\nProcessed in {duration:.2f}s.")

    if errors and not files_count:
         sys.exit(1) # Exit with error code if only errors occurred


if __name__ == "__main__":
    import time # Add time import here if not already present globally
    main()
# --- END OF FILE text-to-codebase.py ---